import { StyleSheet } from 'react-native';
import { AppTheme } from '../../ui/theme';

export const filesStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  pathBar: {
    marginTop: 2,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 8,
    shadowColor: '#CBD5E1',
    shadowOpacity: 0.3,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  pathBack: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#EAEFF6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pathBackDisabled: {
    backgroundColor: '#F2F4F8',
  },
  pathText: {
    flex: 1,
    color: '#66748A',
    fontSize: 12,
  },
  status: {
    color: '#66748A',
    marginBottom: 4,
  },
  listContent: {
    paddingBottom: 100,
  },
  fileCard: {
    marginBottom: 8,
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#CBD5E1',
    shadowOpacity: 0.32,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  fileVisual: {
    width: 36,
    height: 36,
    borderRadius: 10,
    overflow: 'hidden',
  },
  thumb: {
    width: '100%',
    height: '100%',
  },
  filePlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fileInfo: {
    flex: 1,
  },
  fileName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1E293B',
  },
  fileMeta: {
    marginTop: 1,
    color: '#64748B',
    fontSize: 12,
  },
  moreButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  emptyWrap: {
    marginTop: 52,
    alignItems: 'center',
  },
  emptyText: {
    marginTop: 8,
    color: '#98A3B3',
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 28,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: AppTheme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#2563EB',
    shadowOpacity: 0.35,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
    overflow: 'hidden',
  },
  modalMask: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15,23,42,0.30)',
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  nativeSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 22,
    borderTopWidth: 1,
    borderColor: '#E9EDF2',
  },
  sheetAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 6,
  },
  sheetActionText: {
    fontSize: 16,
    color: '#1E2C45',
  },
  sheetActionDangerText: {
    fontSize: 16,
    color: '#E11D48',
  },
  bottomSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
    borderWidth: 1,
    borderColor: '#E9EDF2',
  },
  bottomSheetTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 10,
  },
  shareTarget: {
    marginBottom: 10,
    color: '#475569',
    fontSize: 13,
  },
  shareLabel: {
    color: '#334155',
    fontSize: 13,
    marginBottom: 6,
    fontWeight: '600',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    fontSize: 14,
    backgroundColor: '#fff',
  },
  bottomSheetButtons: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 8,
  },
  btn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  btnGhost: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#fff',
  },
  btnGhostText: {
    color: '#64748B',
    fontWeight: '600',
  },
  btnPrimary: {
    backgroundColor: AppTheme.colors.primary,
  },
  btnPrimaryText: {
    color: '#fff',
    fontWeight: '700',
  },
  btnDisabled: {
    opacity: 0.6,
  },
  actionPalette: {},
  paletteAction: {},
  paletteText: {},
});
